
database:
  url: "postgresql://dbx_api_service:password@localhost:5432/dbx_aviation"
  echo: true
  pool_size: 5

redis:
  url: "redis://localhost:6379"

api:
  debug: true
  reload: true
  workers: 1

logging:
  level: "DEBUG"
  format: "detailed"

security:
  secret_key: "dev-secret-key-change-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 30
